# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer2.bionic.com:
  orderer3.bionic.com:
  orderer4.bionic.com:
  orderer5.bionic.com:

networks:
  bionic:

services:
  orderer2.bionic.com:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    container_name: orderer2.bionic.com
    networks:
      - bionic
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/bionic.com/orderers/orderer2.bionic.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/bionic.com/orderers/orderer2.bionic.com/tls/:/var/hyperledger/orderer/tls
      - orderer2.bionic.com:/var/hyperledger/production/orderer
    ports:
      - 8050:7050

  orderer3.bionic.com:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    container_name: orderer3.bionic.com
    networks:
      - bionic
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/bionic.com/orderers/orderer3.bionic.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/bionic.com/orderers/orderer3.bionic.com/tls/:/var/hyperledger/orderer/tls
      - orderer3.bionic.com:/var/hyperledger/production/orderer
    ports:
      - 9050:7050

  orderer4.bionic.com:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    container_name: orderer4.bionic.com
    networks:
      - bionic
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/bionic.com/orderers/orderer4.bionic.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/bionic.com/orderers/orderer4.bionic.com/tls/:/var/hyperledger/orderer/tls
      - orderer4.bionic.com:/var/hyperledger/production/orderer
    ports:
      - 10050:7050

  orderer5.bionic.com:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    container_name: orderer5.bionic.com
    networks:
      - bionic
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/bionic.com/orderers/orderer5.bionic.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/bionic.com/orderers/orderer5.bionic.com/tls/:/var/hyperledger/orderer/tls
      - orderer5.bionic.com:/var/hyperledger/production/orderer
    ports:
      - 11050:7050
