OrdererOrgs:
  - Name: Org
    Domain: bionic.com
    EnableNodeOUs: false

    Specs:
      - Hostname: orderer
PeerOrgs:
  - Name: Org1
    Domain: org1.bionic.com
    EnableNodeOUs: false
    Template:
      Count: 2
      # Start: 5
      # Hostname: {{.Prefix}}{{.Index}} # default
    Users:
      Count: 1
