# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:
  orderer.bionic.com:
    container_name: orderer.bionic.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
      - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../crypto-config/ordererOrganizations/bionic.com/orderers/orderer.bionic.com/msp:/var/hyperledger/orderer/msp
      - ../crypto-config/ordererOrganizations/bionic.com/orderers/orderer.bionic.com/tls/:/var/hyperledger/orderer/tls
      - orderer.bionic.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.org1.bionic.com:
    container_name: peer0.org1.bionic.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org1.bionic.com
      - CORE_PEER_ADDRESS=peer0.org1.bionic.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.bionic.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.bionic.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.bionic.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/org1.bionic.com/peers/peer0.org1.bionic.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/org1.bionic.com/peers/peer0.org1.bionic.com/tls:/etc/hyperledger/fabric/tls
      - peer0.org1.bionic.com:/var/hyperledger/production
    ports:
      - 7051:7051

  peer1.org1.bionic.com:
    container_name: peer1.org1.bionic.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org1.bionic.com
      - CORE_PEER_ADDRESS=peer1.org1.bionic.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.org1.bionic.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.bionic.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.bionic.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/org1.bionic.com/peers/peer1.org1.bionic.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/org1.bionic.com/peers/peer1.org1.bionic.com/tls:/etc/hyperledger/fabric/tls
      - peer1.org1.bionic.com:/var/hyperledger/production

    ports:
      - 8051:8051
